# Generated by Django 5.0.1 on 2024-03-21 18:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=core.models.sites_image_upload)),
                ('location', models.ImageField(upload_to=core.models.locations_image_upload)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('map_link', models.URLField(max_length=250)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.destination')),
            ],
        ),
    ]
