# Generated by Django 5.0.1 on 2024-03-28 20:44

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=core.models.events_image_upload)),
                ('price', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('ticket_link', models.URLField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.destination')),
            ],
        ),
    ]
